DEV: added MCH_Staff model, poetry.lock should contain psycopg2, chaned settings.py to connect to postgres database on localhost
dfg-care-somalia/caresomalia-maternal-delivery-backend pull request #9
Opened 2021-04-27 23:52 UTC by AndreaHabib

2021-04-28 00:12 UTC, AndreaHabib commented on README.md
> +poetry add psycopg2
oh yeah right my bad :+1:

2021-04-28 02:13 UTC, dhyxy commented
@AndreaHabib I just added a few snippets that might make the setup a bit easier, let me know what you think!

2021-04-28 02:29 UTC, AndreaHabib commented
That looks way better now, i was actually gonna ask u how to use settings.ini as env var 😅, but yeah nice stuff

2021-04-28 04:07 UTC, dhyxy commented
@AndreaHabib was trying to switch u over to be a reviewer 😅 let me know how this looks, I just renamed it to follow [this](https://stackoverflow.com/questions/385895/django-model-naming-convention). it shows up like this in the admin page now 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/58804183/116345239-fb729e00-a7a4-11eb-9c8b-6f35830b24b9.png">

2021-04-28 04:15 UTC, AndreaHabib commented
I have no idea what ur doing with the migrations, but yeah i will take a look at them tomorrow

2021-04-29 00:00 UTC, dhyxy requested changes

2021-04-29 00:02 UTC, dhyxy commented on caresomalia/api/models.py
> +class AssignPatient(models.Model):
@AndreaHabib do you think we should rename this to `PatientAssignment` by any chance or nah?

2021-05-04 01:07 UTC, dhyxy approved these changes

2021-05-04 01:07 UTC, merged